server:
  name: go-backoffice
  port: 8080

mongo:
  uri: mongodb://localhost:27017
  database: location

log:
  level: info
  map:
    time: "@timestamp"
    msg: message

middleware:
  log: true
  skips: /health
  request: request
  response: response
  size: size
