server:
  name: go-backoffice
  port: 8080
  secure: false
  key: 'configs/key.pem'
  cert: 'configs/cert.pem'
allow:
  origins: '*'
  credentials: true
  methods: GET,PUT,POST,DELETE,OPTIONS,PATCH
  headers: Access-Control-Allow-Headers,Authorization,Origin,Accept,X-Requested-With,Content-Type,Access-Control-Request-Method,Access-Control-Request-Headers

mongo:
  uri: mongodb+srv://dbUser:Demoaccount1@projectdemo.g0lah.mongodb.net
  database: location

log:
  level: info
  map:
    time: "@timestamp"
    msg: message

middleware:
  log: true
  skips: /health
  request: request
  response: response
  size: size
